### ISSUE TITLE
Can't run with latest node and gulp

### ISSUE THREAD

**Issue by monajafi** [auth0-blog/ng1-dinos#1]
The gulp packages are outdated and running with latest versions also gives an error on build I highly appreciate if you can update repo. I get following error:
```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Volumes/Develop/web/migration/ng1-dinos/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Volumes/Develop/web/migration/ng1-dinos/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Volumes/Develop/web/migration/ng1-dinos/gulpfile.js:214:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at requireOrImport (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
```

**Comment by monajafi** [comment]
Fixed issue by upgrading  gulp.js to gulp4 syntax:
gulp.js changes:
```
gulp.task('js',gulp.series('jsVendor', 'jsUser', 'jsAngular'));
gulp.task('default', gulp.series('serve', 'styles', 'js',defaultTask));
```
